#!/usr/bin/env python
# -*- coding: utf-8 -*-

#Juego de cartas en el que hay dos jugadores que se generan dos cartas aleatoriamente y el que tenga el número mas grande gana.

#importamos random para que lo haga aleatoriamente.
import random

salir= False

#Creamos las listas.
numeros=[1,2,3,4,5,6,7,8,9,10,"J","Q","K"]

palos=["D","C","T","P"]

numeros.append("J")
numeros.append("Q")
numeros.append("K")

palos.append("D")
palos.append("C")
palos.append("T")
palos.append("P")

while(salir==False):
	
#Random choice es para que te genere un numero al azar de la lista numeros y palos.
  
	jugador1=random.choice(numeros)
	jugador2=random.choice(numeros)
	
	palo1=random.choice(palos)
	palo2=random.choice(palos)
	

      
#Aqui calculamos quien gana y quien empata.
				
	if(jugador1==jugador2):
		
			print "¡Empate!"
			print "El jugador 1 tiene un", jugador1, "de", palo1
			print "EL jugador 2 tiene un", jugador2, "de", palo2
			print "HAS EMPATADO"
	else:
		if(jugador1 > jugador2):
		
			print "El jugador 1 tiene un", jugador1, "de", palo1
			print "EL jugador 2 tiene un", jugador2, "de", palo2
			print "¡Ha ganado el jugador 1!"
		else:	
			print "El jugador 1 tiene un", jugador1, "de", palo1
			print "EL jugador 2 tiene un", jugador2, "de", palo2
			print "¡Ha ganado el jugador 2!"
			
	salir=True
